#!/usr/bin/bash
./test.pl -v $1 > fe.json
while true; do
  cat fe.json \
  | jq '
    .Variable 
    | .[] 
    | if .type == "f" 
      then 
        [.Name, .Scope[].s, .Scope[].e]  
      else 
        empty 
      end 
    | join(",")
  ' \
  | sed 's/"//g' \
  | awk -F, '{ printf "%-30s\t\t%s-%s\n", $1, $2, $3 }' \
  | fzf \
  | awk '{print $2}' \
  | awk -F '-' '{printf "%d,%dp\n", $1, $2}' \
  | ed -s $1 \
  > tmp.lua 
  [ -s tmp.lua ] \
  && \
  bat --wrap never --theme gruvbox-dark --pager "less -SR" --tabs 2 tmp.lua \
  || break 
done
\rm tmp.lua
\rm fe.json
