#!/usr/bin/bash
./test.pl -v $1 > ve.json 
cat ve.json \
| jq '
  .Variable 
  | .[] 
  | if .type == "v"
    then 
      [.Name, .Scope[].s, .Scope[].e]  
    else 
      empty 
    end 
  | join(",")
' \
| sed 's/"//g' \
| awk -F, '
  { 
    printf "%s", $1; 
    for(i=2; i<=((NF-1)/2 + 1); i=i+1)
    {
      printf "|%s-%s", $i, $((NF-1)/2 + i) 
    } 
    print ""
  }
' \
| column -t -s '|' \
| fzf \
| awk '{ 
    for(i=2; i<=NF; i=i+1)
    {
      printf "%s\n", $i 
    } 
  }' \
| awk -F'-' '
  BEGIN{
  printf "("
  }
  {
    printf "%s|", $1 
  }
  END{
  print ")"
  }
' \
| sed 's/|)$/)/' | sed "s/\(.*\)/'^[[:space:]]*\1'/" \
| xargs -I % sh -c "cat -n $1 | grep -E '%'"
\rm ve.json
